before_script:
  # The following line is only necessary for using a docker-based runner.
  - chmod +x ./gradlew

variables:
  GRADLE_OPTS: "-Dorg:gradle.daemon=false"
  GIT_STRATEGY: clone
  GRADLE_VERSION: "7.5"
  RUNNER: "dalfcs_docker_autoscale"
  JDK_VERSION: "jdk8"

stages:
  - build
  - test
  - deploy

test:
  stage: test
  tags:
    - $RUNNER
  image: gradle:$GRADLE_VERSION-$JDK_VERSION # 7.5-jdk8
  script:
    - ./gradlew check
  only:
    refs:
      - branches

build:
  stage: build
  tags:
    - $RUNNER
  image: gradle:$GRADLE_VERSION-$JDK_VERSION # 7.5-jdk8
  script:
    - ./gradlew assemble --scan
  only:
    refs:
      - branches

deploy-non-prod:
  stage: deploy
  tags:
    - $RUNNER
  image: ruby:3.2-rc
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - export PATH=$PATH:/usr/local/bundle/bin
    - dpl --provider=heroku --app=$heroku_app_name_test --api-key=$heroku_api_key
  only:
    - develop

deploy-prod:
  stage: deploy
  tags:
    - $RUNNER
  image: ruby:3.2-rc
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - export PATH=$PATH:/usr/local/bundle/bin
    - dpl --provider=heroku --app=$heroku_app_name --api-key=$heroku_api_key
  only:
    - main

# Ref: https://dal.brightspace.com/d2l/le/content/230468/viewContent/3095849/View?ou=230468