variables:
  GRADLE_OPTS: "-Dorg:gradle.daemon=false"
  GIT_STRATEGY: clone
  GRADLE_VERSION: 7.5

test:
  stage: test
  tags:
    - dalfcs_docker_autoscale
  image: gradle:$GRADLE_VERSION-jdk17-alpine
  script:
    - chmod +x gradlew
    - ./gradlew check
  only:
    refs:
      - branches

build:
  stage: build
  tags:
    - dalfcs_docker_autoscale
  image: gradle:$GRADLE_VERSION-jdk17-alpine
  script:
    - chmod +x gradlew
    - ./gradlew assemble --scan
  only:
    refs:
      - branches

deploy-int:
  stage: deploy
  tags:
    - dalfcs_docker_autoscale
  image: ruby:3.2-rc
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - export PATH=$PATH:/usr/local/bundle/bin
    - dpl --provider=heroku --app=$heroku_app_name_test --api-key=$heroku_api_key
  only:
    - develop

deploy-prod:
  stage: deploy
  tags:
    - dalfcs_docker_autoscale
  image: ruby:3.2-rc
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - export PATH=$PATH:/usr/local/bundle/bin
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$heroku_api_key
  only:
    - main